# Generated by Django 5.2.6 on 2025-10-26 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('color', models.CharField(default='#d3a15a', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('start_time', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('price_from', models.PositiveIntegerField(default=75000, editable=False)),
                ('team_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='matches.team')),
                ('team_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='matches.team')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=4)),
                ('col', models.PositiveIntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('qr_code_data', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('file_qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='matches.match')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.seatcategory')),
            ],
            options={
                'unique_together': {('match', 'row', 'col')},
            },
        ),
        migrations.CreateModel(
            name='MatchSeatCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.seatcategory')),
            ],
            options={
                'verbose_name': 'Kapasitas Kursi Kategori',
                'verbose_name_plural': 'Kapasitas Kursi Kategori',
                'unique_together': {('match', 'category')},
            },
        ),
    ]
