# Generated by Django 5.2.7 on 2025-10-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSeatCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.seatcategory')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
            options={
                'verbose_name': 'Kapasitas Kursi Kategori',
                'verbose_name_plural': 'Kapasitas Kursi Kategori',
                'unique_together': {('match', 'category')},
            },
        ),
    ]
