# Generated by Django 5.2.7 on 2025-10-23 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatcategory',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='color',
            field=models.CharField(default='#CCCCCC', max_length=7),
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
