# Generated by Django 5.2.7 on 2025-10-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
