# Generated by Django 5.2.7 on 2025-10-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_seat_file_qr_code_seat_qr_code_data'),
        ('matches', '0002_venue_capacity'),
    ]

    operations = [
    ]
