# Generated by Django 5.2.5 on 2025-10-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_seatcategory_match_alter_seatcategory_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatcategory',
            name='match',
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='color',
            field=models.CharField(default='#d3a15a', max_length=7),
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
