# Generated by Django 5.2.7 on 2025-10-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_matchseatcapacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.RemoveField(
            model_name='team',
            name='color',
        ),
        migrations.RemoveField(
            model_name='team',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
        migrations.AlterField(
            model_name='match',
            name='price_from',
            field=models.PositiveIntegerField(default=75000, editable=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
