# Generated by Django 5.2.7 on 2025-10-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_seatcategory_match_alter_seatcategory_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatcategory',
            name='match',
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.JSONField(blank=True, help_text='List of passenger objects: [{name,email,phone,gender,category}, ...]', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='color',
            field=models.CharField(default='#d3a15a', max_length=7),
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
