# Generated by Django 5.2.7 on 2025-10-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='price_from',
            field=models.PositiveIntegerField(default=75000),
        ),
    ]
