# Generated by Django 5.2.7 on 2025-10-24 10:27

import django.core.validators
import django.db.models.deletion
import voucher.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=voucher.models.generate_voucher_code, max_length=20, unique=True, verbose_name='Kode Voucher')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Persentase (%)'), ('FIXED', 'Nilai Tetap (Rp)')], default='FIXED', max_length=7, verbose_name='Tipe Diskon')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nilai Diskon')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pembelian Minimum')),
                ('max_use_count', models.PositiveIntegerField(default=1, verbose_name='Maksimal Penggunaan')),
                ('valid_from', models.DateTimeField(verbose_name='Berlaku Dari')),
                ('valid_until', models.DateTimeField(verbose_name='Berlaku Sampai')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Voucher',
            },
        ),
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.voucher')),
            ],
            options={
                'verbose_name': 'Pelacakan Penggunaan Voucher',
                'verbose_name_plural': 'Pelacakan Penggunaan Voucher',
                'unique_together': {('voucher', 'user')},
            },
        ),
        migrations.AddField(
            model_name='voucher',
            name='used_by',
            field=models.ManyToManyField(blank=True, through='voucher.VoucherUsage', to=settings.AUTH_USER_MODEL, verbose_name='Digunakan Oleh'),
        ),
    ]
