# Generated by Django 5.2.7 on 2025-10-24 06:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('order_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('nama_lengkap_pembeli', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('metode_pembayaran', models.CharField(blank=True, choices=[('BRI', 'BRI'), ('BCA', 'BCA'), ('Mandiri', 'Mandiri'), ('Gopay', 'Gopay'), ('QRIS', 'QRIS')], max_length=10, null=True)),
                ('bukti_transfer', models.ImageField(blank=True, null=True, upload_to='bukti_transfer/')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('CONFIRMED', 'Terbayar'), ('CANCELLED', 'Dibatalkan')], default='PENDING', max_length=10)),
                ('kode_voucher', models.CharField(blank=True, max_length=50)),
                ('tanggal_pembelian', models.DateTimeField(default=django.utils.timezone.now)),
                ('qr_code_data', models.CharField(editable=False, max_length=255, null=True, unique=True)),
                ('file_qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pembelian_set', to='matches.match')),
                ('seats', models.ManyToManyField(related_name='pembelian_set', to='matches.seat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembelian_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
