# Generated by Django 5.2.7 on 2025-10-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembelian',
            name='file_qr_code',
        ),
        migrations.RemoveField(
            model_name='pembelian',
            name='qr_code_data',
        ),
    ]
