# Generated by Django 5.2.5 on 2025-10-23 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_venue_remove_eticket_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('nama_lengkap_pembeli', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('total_harga', models.BigIntegerField(default=0)),
                ('metode_pembayaran', models.CharField(blank=True, choices=[('BRI', 'BRI'), ('BCA', 'BCA'), ('Mandiri', 'Mandiri'), ('Gopay', 'Gopay'), ('QRIS', 'QRIS')], max_length=10, null=True)),
                ('bukti_transfer', models.ImageField(blank=True, null=True, upload_to='bukti_transfer/')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('CONFIRMED', 'Terbayar'), ('CANCELLED', 'Dibatalkan')], default='PENDING', max_length=10)),
                ('kode_voucher', models.CharField(blank=True, max_length=50)),
                ('tanggal_pembelian', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='ticketbuyer',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='name',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='price_bronze',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='price_gold',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='price_silver',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='price_suporter',
        ),
        migrations.AddField(
            model_name='venue',
            name='alamat',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='harga_bronze',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='harga_gold',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='harga_silver',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='harga_suporter',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='kapasitas_maks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='nama_lapangan',
            field=models.CharField(default='DEFAULTP', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemegang', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('kategori_kursi', models.CharField(choices=[('SUPORTER', 'Suporter'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], max_length=10)),
                ('qr_code_data', models.CharField(editable=False, max_length=255, unique=True)),
                ('file_qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tikets', to='payment.pembelian')),
            ],
        ),
        migrations.DeleteModel(
            name='ETicket',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='TicketBuyer',
        ),
    ]
