# Generated by Django 5.2.5 on 2025-10-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_pembelian_remove_payment_user_remove_payment_venue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='order_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='kapasitas_maks',
            field=models.IntegerField(default=0),
        ),
    ]
