# Generated by Django 5.2.5 on 2025-10-24 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_remove_seatcategory_match_alter_seatcategory_color_and_more'),
        ('payment', '0004_alter_pembelian_order_id_alter_venue_kapasitas_maks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.AddField(
            model_name='pembelian',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='matches.match'),
        ),
    ]
