# Generated by Django 5.2.7 on 2025-10-24 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_alter_reply_author_alter_thread_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='reply_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='reply_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='thread_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='thread_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
