# Generated by Django 5.2.7 on 2025-10-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nomor_telepon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
